meta:
  engine: 4.1.0
  version: 1.0.0
  author: TMShader

units:
  keycap: 17
  stagger_unit: cx/3

  orig: cx/2

  # Sheet size: 420x297
  centerShiftX: -2cx
  centerShiftY: -cx

  sheetShiftX: 420/2
  sheetShiftY: -(297/2)

  border_size: 5

  dP: 1
  dsX: 12.2
  dsY: 2cx + stagger_unit - dP + (cx-keycap)
  dpX: dsX/2 + cx/2 + border_size + dP/2 + (cx-keycap)/2
  dpY: stagger_unit/2 + cx/2

  mcuX: 18

points:
  key:
    padding: cx
    spread: cx
    width: keycap
    height: keycap
  zones:
    matrix:
      columns:
        pinky:
          rows.home:
            net: "key_{{name}}"
            led_in: "led_{{name}}"
            led_out: led_matrix_ring_home
          rows.top:
            net: "key_{{name}}"
            led_in: "led_{{name}}"
            led_out: led_matrix_pinky_home
        ring:
          key.stagger: stagger_unit*2
          rows.home:
            net: "key_{{name}}"
            led_in: "led_{{name}}"
            led_out: led_matrix_middle_home
          rows.top:
            net: "key_{{name}}"
            led_in: "led_{{name}}"
            led_out: led_matrix_pinky_top
        middle:
          key.stagger: stagger_unit
          rows.home:
            net: "key_{{name}}"
            led_in: "led_{{name}}"
            led_out: led_matrix_index_home
          rows.top:
            net: "key_{{name}}"
            led_in: "led_{{name}}"
            led_out: led_matrix_ring_top
        index:
          key.stagger: -stagger_unit
          rows.home:
            net: "key_{{name}}"
            led_in: "led_{{name}}"
            led_out: x
          rows.top:
            net: "key_{{name}}"
            led_in: LED_DIN
            led_out: led_matrix_middle_top
      anchor.shift: [centerShiftX + sheetShiftX, centerShiftY + sheetShiftY]

outlines:
  display:
    - what: rectangle
      where: matrix_index_home
      adjust.shift: [dpX, dpY]
      size: [dsX, dsY]

  display_1:
    - what: rectangle
      where: matrix_index_home
      adjust.shift: [dpX, dpY]
      size: [dsX + dP, dsY + dP]

  keys:
    - what: rectangle
      where: true
      size: [keycap, keycap]
      fillet: 2
    - what: outline
      name: display
      operation: stack
      fillet: 1

  board_base:
    - what: rectangle
      where: true
      size: [cx, cx]
      expand: (cx-keycap)/2
      joints: 1

  board:
    - name: board_base
    - what: rectangle
      where: matrix_index_home
      size: [cx*2 + border_size + dsX + dP + (cx-keycap)/2, cx*2 + stagger_unit + cx-keycap]
      adjust.shift: [0.35, dpY]

  pcb_raw:
    - what: outline
      name: board
      expand: border_size - 1.2*3
      joints: 1

  pcb:
    - what: outline
      name: pcb_raw
      fillet: 2.8

  cad_raw:
    - what: outline
      name: board
      expand: border_size
      joints: 1
    - what: rectangle
      where: true
      size: [14, 14]
      operation: stack
    - what: outline
      name: display_1
      operation: stack
    - what: outline
      name: board_base
      operation: stack

  cad_dwg:
    - what: outline
      name: board
      expand: border_size - 1.2*2
      joints: 1
    - name: cad_raw
      operation: stack

  cad:
    raw:
      name: cad_raw
      adjust.shift: [-sheetShiftX, -sheetShiftY]
    hole1: &cad_hole_params
      what: circle
      radius: 3.8/2
      adjust.shift: [-sheetShiftX, -sheetShiftY]
      where: &hole1
        ref: matrix_pinky_top
        shift: [cx/2 - 0.5, -cx/2]
    hole2:
      <<: *cad_hole_params
      where: &hole2
        ref: matrix_middle_top
        shift: [cx/2 - 0.5, -cx/2]

  pcb_cad:
    raw:
      name: pcb
      adjust.shift: [-sheetShiftX, -sheetShiftY]

pcbs:
  artsey_ergo: &pcb_params
    template: kicad8
    outlines:
      main:
        outline: pcb
      case:
        outline: cad_dwg
        layer: Dwgs.User
      display:
        outline: display
        layer: Dwgs.User
    footprints:
      keys:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          hotswap: true
          reversible: true
          choc_v2_support: false
          include_plated_holes: true
          include_choc_v1_led_cutout_marks: false
          from: "GND"
          to: "{{net}}"
          switch_3dmodel_filename: "${SCOTTOKEEBS_KICAD}/3dmodels/ScottoKeebs_Choc.3dshapes/Choc_V1.step"
          switch_3dmodel_xyz_offset: [0, 0, -1.6]
          switch_3dmodel_xyz_rotation: [0, 180, 180]
          hotswap_3dmodel_filename: "${SCOTTOKEEBS_KICAD}/3dmodels/ScottoKeebs_Hotswap.3dshapes/Choc_V1.step"
          hotswap_3dmodel_xyz_offset: [0, 0, -1.65]
          hotswap_3dmodel_xyz_rotation: [0, 180, 180]
          keycap_3dmodel_filename: "../models/Choc_1.00u_CAD_MONO.step"
          keycap_3dmodel_xyz_offset: [0, 0, -11.7]
          keycap_3dmodel_xyz_rotation: [0, 0, 90]

      led: &led_params
        what: ceoloide/led_sk6812mini-e
        where: /^matrix_.*_home$/
        params:
          P2: "{{led_out}}"
          P4: "{{led_in}}"
          reversible: true
          signal_trace_width: 0.2
          gnd_trace_width: 0.2
          vcc_trace_width: 0.3
          via_size: 0.6
          via_drill: 0.3
          led_3dmodel_filename: "${SCOTTOKEEBS_KICAD}/3dmodels/ScottoKeebs_Components.3dshapes/LED_SK6812MINI.step"
          led_3dmodel_xyz_rotation: [90, 0, 180]
        adjust:
          shift: [0, -4.7]
      led-180:
        <<: *led_params
        where: /^matrix_.*_top$/
        adjust.rotate: 180

      nice_nano:
        what: ceoloide/mcu_nice_nano
        where:
          ref: matrix_index_home
          shift: [dpX - 1.2, dpY + 6.8]
        params:
          reversible: true
          reverse_mount: true
          show_via_labels: false
          show_silk_labels: false
          show_silk_labels_on_both_sides: false
          show_instructions: false
          only_required_jumpers: true
          mcu_3dmodel_filename: "${SCOTTOKEEBS_KICAD}/3dmodels/ScottoKeebs_MCU.3dshapes/Nice_Nano_V2_Flipped.step"
          mcu_3dmodel_xyz_offset: [0, 0, -4.2]
          mcu_3dmodel_xyz_rotation: [0, 180, 0]

          P2: OLED_SDA
          P3: OLED_SCL

          P21: key_matrix_middle_top
          P20: key_matrix_index_top
          P19: key_matrix_ring_top
          P18: key_matrix_pinky_top

          P15: key_matrix_middle_home
          P14: key_matrix_ring_home
          P16: key_matrix_pinky_home
          P10: key_matrix_index_home

          P5: LED_DIN

          P2_label: P2
          P3_label: P3
          P5_label: P5

          P10_label: P10
          P14_label: P14
          P15_label: P15
          P16_label: P16
          P18_label: P18
          P19_label: P19
          P20_label: P20
          P21_label: P21

      display:
        what: ceoloide/display_ssd1306
        where:
          ref: matrix_index_home
          shift: [dpX, dpY - 0.8]
        params:
          include_labels: false
          reversible: true
          invert_jumpers_position: false
          SDA: OLED_SDA
          SCL: OLED_SCL
          display_3dmodel_filename: "${SCOTTOKEEBS_KICAD}/3dmodels/ScottoKeebs_Components.3dshapes/OLED_128x32.step"
          display_3dmodel_xyz_rotation: [0, 0, -90]
          display_3dmodel_xyz_offset: [0, 0.8, 4.5]

      battery:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: matrix_middle_home
          shift: [-4, -12.6]
          rotate: 90
        params:
          side: B
          reversible: true
          connector_3dmodel_filename: "${KICAD8_3DMODEL_DIR}/Connector_JST.3dshapes/JST_PH_S2B-PH-K_1x02_P2.00mm_Horizontal.wrl"
          connector_3dmodel_xyz_rotation: [0, 0, -180]
          connector_3dmodel_xyz_offset: [1, 0, 0]

      power:
        what: ceoloide/power_switch_smd_side
        where:
          ref: matrix_index_home
          shift: [10.2, -7.9]
        params:
          side: B
          invert_behavior: false
          reversible: true
          include_silkscreen: false
          switch_3dmodel_filename: "${SCOTTOKEEBS_KICAD}/3dmodels/ScottoKeebs_Components.3dshapes/Switch_MSK12C02.step"
          switch_3dmodel_xyz_rotation: [0, 0, 90]
        adjust:
          rotate: -90
      power_hole-1: &power_hole_params
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_index_home
          shift: [10.2 - 8, -9]
          rotate: 90
        params:
          outline: 0.5
          drill: 1.5
          drill_y: 5
          include_courtyard: true
      power_hole-2:
        <<: *power_hole_params
        where.shift: [10.2 + 8, -9]

      reset:
        what: ceoloide/reset_switch_smd_side
        where:
          ref: matrix_index_top
          shift: [0, 14]
        params:
          side: B
          reversible: true
          include_bosses: true
          switch_3dmodel_filename: "../models/EVQPU-LC-02K.STEP"
          switch_3dmodel_xyz_rotation: [-90, 0, 0]
      reset_hole-1: &reset_hole_params
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_index_top
          shift: [-5.5, 14.5]
        params:
          outline: 0.5
          drill: 1.5
          drill_y: 2.5
          include_courtyard: true
      reset_hole-2:
        <<: *reset_hole_params
        where.shift: [5.5, 14.5]

      fill_zone:
        what: ceoloide/utility_filled_zone
        params:
          side: "F&B"
          corner_smoothing: fillet

      mounting_hole-1:
        what: ceoloide/mounting_hole_npth
        where: *hole1
        params: &hole_params
          hole_size: 5.0
          hole_drill: 5.0
      mounting_hole-2:
        what: ceoloide/mounting_hole_npth
        where: *hole2
        params: *hole_params