---
include:
  - board: nice_nano_v2
    shield: artsey_ergo_left
    snippet: studio-rpc-usb-uart
    artifact-name: artsey_ergo_left

  - board: nice_nano_v2
    shield: artsey_ergo_right
    snippet: studio-rpc-usb-uart
    artifact-name: artsey_ergo_right

  # - board: nice_nano_v2
  #   shield: artsey_ergo_left
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ARTSEY_SPLIT=y
  #   artifact-name: artsey_ergo_split_left

  # - board: nice_nano_v2
  #   shield: artsey_ergo_right
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ARTSEY_SPLIT=y
  #   artifact-name: artsey_ergo_split_right

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings-reset