on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/build-user-config.yml
    with:
      archive_name: zmk-artsey_ergo-firmware
      working_directory: firmware
