name: "ZMK Firmware Build"

on:
  push:
    paths:
      - 'firmware/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'firmware/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-user-config.yml
    with:
      archive_name: zmk-artsey_ergo-firmware
      working_directory: firmware
